.gitignore
README.md

Updates the README.md file, for visitors with explanation of how to install charts from this repository.

chore: update README for github-pages

---

README.md
index.yaml

This updates velocity-operator name in README.md

chore: update velocity-operator name

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/values.yaml

This PR Addresses fix: change repo uri:

fix: change repo uri

---

.github/workflows/testing.yaml
charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/deployment.yaml
charts/velocity-operator/templates/manager-rbac.yaml
charts/velocity-operator/values.yaml

This PR Addresses fix(ENV-4101): bump tag:

fix(ENV-4101): bump tag

---

.github/workflows/testing.yaml
charts/velocity-operator/Chart.lock
charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/manager-rbac.yaml
charts/velocity-operator/values.yaml

documented at [link](https://github.com/helm/chart-testing/blob/main/doc/ct_install.md)

ci: add upgrade test when installing chart

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/manager-rbac.yaml
charts/velocity-operator/values.yaml

This PR Addresses fix: fix ingress permissions:
* fixed ingress api group

fix: fix ingress permissions

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/values.yaml

This PR Addresses chore: bump version:

chore: bump version

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/manager-rbac.yaml
charts/velocity-operator/values.yaml

This PR Addresses chore: bump crd permissions:
Added crd permissions

chore: bump crd permissions

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/manager-rbac.yaml

This PR Addresses chore(ENV-4462): add rbac:

chore(ENV-4462): add rbac

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/_helpers.tpl
charts/velocity-operator/templates/deployment.yaml

This PR Addresses feat(ENV-4323): add s3 crd destroy provider:

feat(ENV-4323): add s3 crd destroy provider

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/values.yaml

This PR Addresses chore: bump operator image 0.0.6:

chore: bump operator image 0.0.6

---

charts/velocity-operator/templates/deployment.yaml

This PR Addresses fix: scret name:

fix: scret name

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/aws-cred-developer.yaml
charts/velocity-operator/values.yaml

This PR Addresses chore(ENV-4516): support cloud resources:
* Increase version
* .
* .
* .
* Create new secret for services

chore(ENV-4516): support cloud resources

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.1.1

chore(operator-release): update operator image for v1.1.1

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.1.2

chore(operator-release): update operator image for v1.1.2

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.1.4

chore(operator-release): update operator image for v1.1.4

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.1.5

chore(operator-release): update operator image for v1.1.5

---

.github/workflows/CODEOWNERS
charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/manager-rbac.yaml

This PR Addresses feat(ENV-4658): add batch group to rbac:
* feat: add batch group api to rbac

feat(ENV-4658): add batch group to rbac

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.3.0

chore(operator-release): update operator image for v1.3.0

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.5.1

chore(operator-release): update operator image for v1.5.1

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.5.2

chore(operator-release): update operator image for v1.5.2

---

charts/velocity-operator/Chart.yaml
charts/velocity-registry/Chart.yaml
charts/velocity-registry/templates/_helpers.tpl
charts/velocity-registry/templates/registry-auth.yaml
charts/velocity-registry/templates/registry-docker-config.yaml
charts/velocity-registry/values.yaml

1. updating registry chart  - removing secrets yaml's and values
2. updating app version - from 1.5.3 the secrets will be created by the operator.

fix(ENV-4761): updating app verions and removing secrets and values from registry

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.5.4

chore(operator-release): update operator image for v1.5.4

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.6.0

chore(operator-release): update operator image for v1.6.0

---

charts/velocity-operator/values.yaml

fixing description comment for the region values.

fixing region description

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.6.2

chore(operator-release): update operator image for v1.6.2

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.6.3

chore(operator-release): update operator image for v1.6.3

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.7.0

fix(operator-release): update operator image for v1.7.0

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.7.1

chore(operator-release): update operator image for v1.7.1

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/values.yaml

This PR Addresses feat(ENG-34): operator dogfooding chart version:
* feat: change default allowAll 
* chore: bump version

feat(ENG-34): operator dogfooding chart version

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.9.0

chore(operator-release): update operator image for v1.9.0

---

.github/workflows/testing.yaml
charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/manager-rbac.yaml
charts/velocity-operator/values.yaml

This PR Addresses feat(ENG-150): increase requests:
* feat: increase requests 
* feat: change verbs to '*' to really allow all

feat(ENG-150): increase requests and allow all verbs RBAC

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.10.0

chore(operator-release): update operator image for v1.10.0

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.10.2

chore(operator-release): update operator image for v1.10.2

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.10.3

chore(operator-release): update operator image for v1.10.3

---

charts/velocity-operator/Chart.yaml

chore(operator-release): update operator image for v1.10.4

chore(operator-release): update operator image for v1.10.4

---

charts/velocity-operator/Chart.yaml
charts/velocity-operator/templates/deployment.yaml
charts/velocity-operator/values.yaml

This PR Addresses feat(ENG-40): allow running as root:
* feat: allow running as root

feat(ENG-40): allow running as root

---

charts/operator/Chart.yaml

This PR was created by a GitHub Action: https://github.com/techvelocity/starlink/actions/runs/10027790097

Release operator 0.1.0-rc2
